### ISSUE TITLE
store: implement streaming queries

### ISSUE THREAD

**Issue by peterbourgon** [oklog/oklog#10]
There are lots of use cases that are well-served by streaming queries. That is, set up a query that delivers results as they arrive at each store node. At a first thought this would look like

- User makes a stream-type query to any store node
- The store node broadcasts that query to all store nodes
- Each store node registers the query in some kind of table as a websocket
- When new segments are replicated, records are matched against each registered streaming query
- Matching records are written to the websocket
- The originating store node uses some kind of ringbuffer to deduplicate records over a time window
- Every effort should be made to keep the websocket connections alive: reconnect logic, etc.

**Comment by josephglanville** [comment]
Unless you have already settled on Websockets it's probably worth considering [SSE](https://en.wikipedia.org/wiki/Server-sent_events)  instead. It's significantly more light weight and I think more suited to what you are trying to achieve here.

**Comment by peterbourgon** [comment]
Yeah, I won't be using websockets, that was just exemplary :) At the moment it looks like a plain old streaming response with Transfer-Encoding: chunked should fit the bill, but if I need more than that I'll probably do SSE, thanks for the reminder.

**Comment by peterbourgon** [comment]
This isn't done yet.

**Comment by xla** [comment]
While likely an edge-case there should be awareness of what kind of behaviour is expected when topology changes (store nodes join/leave) happen during an active streaming query.

**Comment by peterbourgon** [comment]
Yep, that's accounted for. New nodes get picked up within some interval (currently a few seconds) and start forwarding matching segments. Nodes that go away get removed from the active query within the same interval.

**Comment by xla** [comment]
> Yep, that's accounted for. New nodes get picked up within some interval (currently a few seconds) and start forwarding matching segments. Nodes that go away get removed from the active query within the same interval.

\0/

**Comment by jtarchie** [comment]
In relation to the discussion of SSE, websocket, etc, please put a good abstraction on the transport interface. Depending on different requirements, authentication, TLS, etc. transports can be useful.

A project that has a good abstraction is [mango](https://github.com/go-mangos/mangos/tree/master/transport) for multiple transports.

**Comment by peterbourgon** [comment]
It'll be plain HTTP/1.1 Transfer-Encoding: Chunked.

**Comment by peterbourgon** [comment]
Implemented!
