### ISSUE TITLE
new Jenkins plugin and question about TCP connections

### ISSUE THREAD

**Issue by timwebster9** [oklog/oklog#101]
Hi @peterbourgon 

I've written a Jenkins plugin to send console logs to OK Log.  The reason for yet another Jenkins plugin is all the existing ones are specific to their logging stacks - e.g. Splunk, Logstash, ELK, etc.  This one is generic in that all it requires is a remote host/TCP port to connect to.

Although it works, it needs some fine-tuning.  I have a question regarding the socket connections to the ingester.

If I open a socket connection and don't use it for a couple of minutes, I get a broken pipe error.  This is sort of OK, as I can just re-create the socket.  But what I wanted to avoid was having to check/recreate the socket for every message, which it kind of looks like I might have to do since it happens so frequently.  So I guess the question is - I don't know what's causing the broken pipe, and is there a timeout on the server side that could be causing this?

**Comment by timwebster9** [comment]
After a bit more digging it looks like the server is sending a FIN packet at just under a minute.  OK no problem I've dealt with it.  I haven't 'officially' released the plugin but it's in a working state here if anyone is interested: https://github.com/timwebster9/jenkins-tcp-log-fowarder-plugin.

**Comment by peterbourgon** [comment]
🎉
