### ISSUE TITLE
go get install failing due to missing flock dependency

### ISSUE THREAD

**Issue by moderation** [oklog/oklog#105]
Prometheus just removed the util/flock direction - https://github.com/prometheus/prometheus/pull/3853

This causes an oklog install or update using `go get -u github.com/oklog/oklog/cmd/oklog` to fail with a missing dependency.

I know Peter discourages installation like this however this will need to be fixed for the next binary release.

**Comment by peterbourgon** [comment]
Oh dang, thanks for the catch. I'll probably need to mirror it here.
