### ISSUE TITLE
invalid cross-device link

### ISSUE THREAD

**Issue by jozuenoon** [oklog/oklog#110]
Hi,

We have oklog v0.3.0 running in docker. I'm mounting external disk on `/data`. After while I get below error:
```
ts=2018-03-22T11:27:58.697719584Z level=info ingest_path=data/ingest
during recovery: rename data/store/0093a279-2977-42ec-b9d3-7771d4551950.active 01C96FFQG2W35WWA9VMPKCGCG1-01C96FFTAXR3F5QW47JTJGRQPS.flushed: invalid cross-device link
```

I know this is because it tries to use `os.Rename` cross disks, however I'm not fully understanding why oklog want to move file outside `data` folder (which is disk on it's own). I could replace `Rename` method to handle it with `io.Copy` instead, but best solution would be to avoid moving files outside `data` folder in first place.

**Comment by jozuenoon** [comment]
This issue is fixed on `master`:

https://github.com/oklog/oklog/blob/master/pkg/store/file_log.go#L414

v0.3.0 is broken.

**Comment by peterbourgon** [comment]
Thanks, I'll make a new release now.
