### ISSUE TITLE
network

### ISSUE THREAD

**Issue by gedw99** [oklog/oklog#124]
this looks good for iot stuff.

is the network transport and serialisation plug-able to a dgeree ?
for example mqtt bridge etc ?

**Comment by peterbourgon** [comment]
Nope! Definitely not.

**Comment by peterbourgon** [comment]
Well, if you're talking IoT, then the only "network" you probably care about is forwarder -> ingester. It would be easy to stick some kind of adapter in front of the ingesters which consume from MQTT or whatever. But definitely out of scope for the core project.
