### ISSUE TITLE
Integration with Fluentd

### ISSUE THREAD

**Issue by jvassev** [oklog/oklog#126]
Hi,
how is it possible to let fluentd output to an oklog server? I know fluent can export over http using an output plugin like https://github.com/ento/fluent-plugin-out-http#configuration-options but I am not sure how to configure it in the context of oklog. 

Which port and/or uri should when the target is oklog?

Thanks,
Julian

**Comment by peterbourgon** [comment]
The default port for ingesters is 7651. You want it to emit raw records over TCP, with a newline delimiter between records. This is probably _not_ `type http` but probably something else. I'm not familiar enough with fluentd to say what it could be.
