### ISSUE TITLE
Log records can be stored in wrong order

### ISSUE THREAD

**Issue by dmitry-guryanov** [oklog/oklog#128]
Hello,

I've found that log records could come in wrong order sometimes.

Suppose we have one ingestor and 2 forwarders (A and B), store node is offline at the beginning. If for example, ingestor will save two segments, one - from A in time range 2-5 and second - from B in time range 3-6. Than if we start store, it will start fetching segments and appending them to "active" (Consumer.active in the code). This buffer will have records in time range 2-5-3-6 and these records will never be reordered if I understood code correctly. So as a result  we'll see query output like:

    default aaaaaaaaa 2018-06-13T18:07:11+03:00 foo 000000197 G
    default aaaaaaaaa 2018-06-13T18:07:11+03:00 foo 000000198 J
    default aaaaaaaaa 2018-06-13T18:07:11+03:00 foo 000000199 F
    default bbbbbbb 2018-06-13T18:07:09+03:00 foo 000000150 T
    default bbbbbbb 2018-06-13T18:07:09+03:00 foo 000000151 N
    default bbbbbbb 2018-06-13T18:07:09+03:00 foo 000000152 S

I suppose this behaviour in not expected, so maybe it need to be fixed.
I would be very grateful to someone who'll clarify it.

**Comment by dmitry-guryanov** [comment]
I want all log records to be sorted by time. Now sometimes you can get wrong order, like in example above:

    default aaaaaaaaa 2018-06-13T18:07:11+03:00 foo 000000199 F
    default bbbbbbb 2018-06-13T18:07:09+03:00 foo 000000150 T

If you replace this line https://github.com/oklog/oklog/blob/master/pkg/store/consume.go#L223 by `return c.replicate` all segments will be merged by `mergeRecords` with establishing global order, so all lines in query output will be sorted.

**Comment by dmitry-guryanov** [comment]
But in line https://github.com/oklog/oklog/blob/master/pkg/store/consume.go#L208 you provide only one reader to `mergeRecords` function, so it won't sort records and will just append new segment to existing buffer.

**Comment by peterbourgon** [comment]
mergeRecords takes the current set of records (c.active) and the new records to merge in to them (readResp.Body). The records are sorted by mergeRecords.

**Comment by dmitry-guryanov** [comment]
Sorry, but I don't understand, how it can modify `c.active`. `mergeRecords` takes `io.Writer` as its first argument, you can only append data to `bytes.Buffer` using this interface. All records in `c.active` will remain unchanged.

Here is comment for `mergeRecords`:
    // mergeRecords takes a set of io.Readers that contain ULID-prefixed records in
    // individually-sorted order, and writes the globally-sorted output to the
    // io.Writer.
