### ISSUE TITLE
Proposal: Create ULID from timestamp contained in record

### ISSUE THREAD

**Issue by oliverhausler** [oklog/oklog#133]
When logging from a multi-threaded language like Java, multiple loggers may collect and forward logs, which means, when these are inserted:

- the lines may not be in sequence.
- the lines may be delayed.

If we stamp such records after ingest, we add a second (global) timestamp, which is not the true time when the record has been produced.

Global timestamps let us account for clock skew to compare between multiple log sources when we query logs, but it's much more important that logs from the same source are in sequence and carry the correct timestamp of when they have been produced on the originating system.

I would propose:

Instead of creating and prepending the ULID locally, assume that each record is stamped with an epoch timestamp (first characters) and replace that timestamp with the ULID (which uses the epoch timestamp as input).

**Comment by peterbourgon** [comment]
Sorry, absolutely not.
