### ISSUE TITLE
Unable to "make install" using the tar.gz package and no oklog command found

### ISSUE THREAD

**Issue by Hochman85** [oklog/oklog#140]
Hi,

Maybe a basic question: I am unable to "make install" from the tar.gz package (after unarchiving it). Also, there doesn't seem to be any oklog command (there's a folder cmd full of .go files and I don't want to install more dependencies to be able to get started and build).

Alternatively, is there an easier way for me to get started and test OkLog? On the homepage, there doesn't seem to be any instructions on what to do before starting to use the command "oklog" (before Small/Large installation).

Thanks,
Hoch.

**Comment by peterbourgon** [comment]
> Maybe a basic question: I am unable to "make install" from the tar.gz package (after unarchiving it). Also, there doesn't seem to be any oklog command (there's a folder cmd full of .go files and I don't want to install more dependencies to be able to get started and build).

The .tar.gz is source files. Download the appropriate binary release for your architecture, and `chmod +x` it. You should then be able to run e.g. `./oklog-linux-amd64 -h`.

**Comment by Hochman85** [comment]
Thanks! Hadn't seen the release page. Just started using one of the binaries from there.
