### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by derekperkins** [oklog/oklog#22]
Would it make sense to use gRPC instead of POSTing data?

**Comment by peterbourgon** [comment]
Between which components?

**Comment by derekperkins** [comment]
Anywhere really, but particularly shipping from the ingest nodes to the storage nodes.

**Comment by peterbourgon** [comment]
What problems are you encountering that gRPC would solve? :)

**Comment by peterbourgon** [comment]
Hopefully this answers the question! :)
