### ISSUE TITLE
Tag or label feature

### ISSUE THREAD

**Issue by nooproblem** [oklog/oklog#33]
Hi,

Just wondering if there was any ideas on how distinguish between very similar logs that are pulled / pushed from multiple log endpoints? At the moment I am unable to find a way to distinguish between very similar logs, unless the log records happen to include something like a host name/IP, but then I could be missing something obvious. Is there any metadata added by the log forward feature? If not, might tags / labels added by the forward feature be a possible solution or would this be out of scope?

Thanks to Peter for the great idea and all the work so far. I am looking forward to see how oklog evolves in the future. 👍

**Comment by peterbourgon** [comment]
Annotations are totally supported, but should be done in your log pipeline, for example logstash. By the time OK Log is involved we treat all log records as opaque byte slices. Hope that helps!

**Comment by peterbourgon** [comment]
Taken from [another comment](https://github.com/oklog/oklog/pull/25#issuecomment-275613618),

I'd be happy to add basic annotation to `oklog forward` . . . What do you think of a repeatable flag, like

```
myservice | oklog forward -prefix $(hostname) -prefix $MY_ENV_VAR ...
```

Creating log lines like

```
nydata03a MYVALUE 2016-01-26 12:34:56 [DEBUG] reticulating splines...
```
