### ISSUE TITLE
multiple processes to a single forwarder

### ISSUE THREAD

**Issue by jtarchie** [oklog/oklog#36]
What would be the best practice for multiple processes that want to forward the logs?

A VM can have multiple processes running. Having a single forwarder for each process seems like overkill.

Ideally, I feel like a single forwarder should be able to handle it.

I thought about using a single named piped that things could write to and the forward reads from. There are limitations in a named pipe though.

I like that the process can just write to STDIN of a forward, that way it does not have to worry about back pressure itself. It is always the kernal and the forward's worry.

Any leads for a convention?

**Comment by peterbourgon** [comment]
A forwarder does nothing more than `netcat` would. Why would it be overkill to have one per process?  This is the pattern employed by e.g. [svlogd](http://smarden.org/runit/svlogd.8.html) and many other logging pipeline systems.

**Comment by jtarchie** [comment]
Is there a reason not to have one process for multiple writers?

The reasoning is that our deployments can have very specific allocations on them. Each process needs a certain amount of CPU, disk space, memory, etc. The overhead of adding a forward for each process can cause a lot of context switching for kernel.

Is it more expensive to have a many processes [`select`](http://man7.org/linux/man-pages/man2/select.2.html) from a single pipe or have a single process `select` from many pipes? That is an honest question, I don't know.

The work we've done with the [metron forwarder](https://github.com/cloudfoundry/loggregator/blob/develop/src/metron/main.go) is about having one process read from multiple sources.

**Comment by peterbourgon** [comment]
> The overhead of adding a forward for each process can cause a lot of context switching for kernel.

I'll take your word for it—but I'm not really convinced without concrete e.g. profiling data :)

The main reason to use a single forwarder per process (service) is because it's the most straightforward way to abide the [12factor rule of logs as streams](https://12factor.net/logs). There's certainly nothing wrong with running a single forwarder for multiple processes (services), if it's not too complicated. But I don't have any specific recommendations.

**Comment by josephglanville** [comment]
@jtarchie you could write a plugin for your existing forwarder that connects to and forwards to the ingest nodes. This would allow you to continue to capture the logs from multiple processes (or harvest from log files) and forward to oklog.
