### ISSUE TITLE
Syslog integration

### ISSUE THREAD

**Issue by mattkanwisher** [oklog/oklog#44]
Is there any pattern for integrating syslog streams into this? If not would you be interested in a patch that accepted the syslog protocol ? This seems to be a standard way to handle containers

**Comment by peterbourgon** [comment]
All the OK Log ingest endpoints care about is receiving newline-delimited records. Correct me if I'm wrong, but syslog already meets this contract. If that's true, anything which emits syslog should already be fully compatible with OK Log.

**Comment by mattkanwisher** [comment]
So also Syslog supports structured logging via Json, your probably aware as your other framework does it https://github.com/go-kit/kit/blob/master/log/json_logger.go . I couldn't find anything about OKLog supporting structured logs?

**Comment by peterbourgon** [comment]
OK Log treats log records as opaque byte-slices. The query interface is grep. You're free to send structured logs, unstructured logs, or anything you want into it, as long as each record is newline-delimited.

**Comment by peterbourgon** [comment]
We had a rousing discussion [on Twitter](https://twitter.com/kanwisher/status/835783587521675264), from that I've [updated the README](https://github.com/oklog/oklog/commit/f50392c) with some details about querying structured logs, anything more than that is not on a concrete roadmap, though I'm curious about what structured log parsing "plugins" might look like at the query or storage layer...

**Comment by roondar** [comment]
From this code: https://gist.githubusercontent.com/marcelom/4218010/raw/53b643bd056d03ffc21abcfe2e1b9f6a7de005f0/pysyslog.py

<pre>
#!/usr/bin/env python

## Tiny Syslog Server in Python.
##
## This is a tiny syslog server that is able to receive UDP based syslog
## entries on a specified port and save them to a file.
## That's it... it does nothing else...
## There are a few configuration parameters.

HOST, PORT = "0.0.0.0", 514

import SocketServer
import sys


class SyslogUDPHandler(SocketServer.BaseRequestHandler):

        def handle(self):
                data = bytes.decode(self.request[0].strip())
                socket = self.request[1]
                print( "%s : " % self.client_address[0], str(data))
                sys.stdout.flush()

if __name__ == "__main__":
        try:
                server = SocketServer.UDPServer((HOST,PORT), SyslogUDPHandler)
                server.serve_forever(poll_interval=0.5)
        except (IOError, SystemExit):
                raise
        except KeyboardInterrupt:
                print ("Crtl+C Pressed. Shutting down.")

</pre>

Then run :  python2 ./pysyslog.py |  oklog forward localhost
