### ISSUE TITLE
Tail-like behaviour

### ISSUE THREAD

**Issue by zoobenthos** [oklog/oklog#46]
I think it may be useful if oklog have possibility to get some last lines from logs without specifying from/to datetime. Can I get this functionality with current version or it is impossible now?

**Comment by peterbourgon** [comment]
You can stream, see https://github.com/oklog/oklog/pull/34. But there's no way to query for the last N records right now, because that's not how things are structured on disk. We could emulate it, but it would be inefficient. I would prefer not to offer that as an API for the time being.

**Comment by zoobenthos** [comment]
Ok, thanks for clarifying! I will close this issue but simply imagine most common case for integration usage such log system as oklog - it is been simply view tail via web interface or commandline. Without this functionality we're got no logs or too many logs with one single query. Not very usable.
