### ISSUE TITLE
ingeststore non functional

### ISSUE THREAD

**Issue by newhook** [oklog/oklog#51]
Following the directions in the README I've setup two hosts to test ingeststore. After starting the hosts I get:

```
tthew@log-store-1:~$ oklog ingeststore -cluster log-store-1 -peer log-store-1 -peer log-store-2
ts=2017-03-30T17:36:20.410582124Z level=info cluster=log-store-1:7659
ts=2017-03-30T17:36:20.410667763Z level=info fast=tcp://0.0.0.0:7651
ts=2017-03-30T17:36:20.410689283Z level=info durable=tcp://0.0.0.0:7652
ts=2017-03-30T17:36:20.410707298Z level=info bulk=tcp://0.0.0.0:7653
ts=2017-03-30T17:36:20.410733243Z level=info API=tcp://0.0.0.0:7650
ts=2017-03-30T17:36:20.410890213Z level=info ingest_path=data/ingest
ts=2017-03-30T17:36:20.410950353Z level=info store_path=data/store
ts=2017-03-30T17:36:20.421332098Z level=debug component=cluster Join=1
ts=2017-03-30T17:36:20.521814528Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:36:21.522022322Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:36:22.522240947Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:36:23.621790312Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:36:24.621966192Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:36:25.42175071Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:36:25.622150195Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:36:26.721837292Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:36:27.722031419Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:36:28.722254832Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:36:29.821805223Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
```

....

```
matthew@log-store-2:~$ oklog ingeststore -cluster log-store-2 -peer log-store-1 -peer log-store-2
ts=2017-03-30T17:36:34.307731343Z level=info cluster=log-store-2:7659
ts=2017-03-30T17:36:34.307863365Z level=info fast=tcp://0.0.0.0:7651
ts=2017-03-30T17:36:34.307892432Z level=info durable=tcp://0.0.0.0:7652
ts=2017-03-30T17:36:34.307917061Z level=info bulk=tcp://0.0.0.0:7653
ts=2017-03-30T17:36:34.307940364Z level=info API=tcp://0.0.0.0:7650
ts=2017-03-30T17:36:34.308098722Z level=info ingest_path=data/ingest
ts=2017-03-30T17:36:34.308193966Z level=info store_path=data/store
ts=2017-03-30T17:36:34.319719011Z level=debug component=cluster Join=2
ts=2017-03-30T17:36:41.420291562Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:36:42.420504608Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
^Cts=2017-03-30T17:36:43.420713048Z level=debug component=Compacter shutdown_took=7.052µs
received signal interrupt
```

**Comment by peterbourgon** [comment]
I'm having trouble parsing that output. Can you start both nodes exactly as you have there, let them both run for 30 seconds, ctrl-C them, and paste the logs?

**Comment by newhook** [comment]
matthew@log-store-1:~$ oklog ingeststore -cluster log-store-1 -peer log-store-1 -peer log-store-2 --store.path=/data/logs
ts=2017-03-30T17:56:15.896240075Z level=info cluster=log-store-1:7659
ts=2017-03-30T17:56:15.896395422Z level=info fast=tcp://0.0.0.0:7651
ts=2017-03-30T17:56:15.89646065Z level=info durable=tcp://0.0.0.0:7652
ts=2017-03-30T17:56:15.896534986Z level=info bulk=tcp://0.0.0.0:7653
ts=2017-03-30T17:56:15.896558566Z level=info API=tcp://0.0.0.0:7650
ts=2017-03-30T17:56:15.896721494Z level=info ingest_path=data/ingest
ts=2017-03-30T17:56:15.896886766Z level=info store_path=/data/logs
ts=2017-03-30T17:56:15.911911006Z level=debug component=cluster Join=1
ts=2017-03-30T17:56:16.012391721Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:22.912355914Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:23.912656329Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:24.912837265Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:25.912354747Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:26.012395986Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:27.012625222Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:28.012831573Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:29.11237297Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:30.112549271Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:30.912289492Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:31.112726507Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:32.212393645Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:33.21259064Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:34.212794311Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:35.312382736Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:35.912331321Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:36.312568916Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:37.312766935Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:38.412393209Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:39.41262957Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:40.412821045Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:40.91228721Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:41.512395426Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:42.512567351Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:43.512837809Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:44.612445675Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:45.612638711Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:45.912275081Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:46.612839811Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:47.712340097Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:48.712506747Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:49.712752413Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:50.81240363Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:50.912261664Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:51.812679162Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
^Cts=2017-03-30T17:56:52.812935046Z level=debug component=Compacter shutdown_took=15.8µs
received signal interrupt

matthew@log-store-2:~/go/src/github.com/oklog/oklog$ oklog ingeststore -cluster log-store-2 -peer log-store-1 -peer log-store-2 --store.path=/data/logs
ts=2017-03-30T17:56:16.335116367Z level=info cluster=log-store-2:7659
ts=2017-03-30T17:56:16.335552731Z level=info fast=tcp://0.0.0.0:7651
ts=2017-03-30T17:56:16.335667287Z level=info durable=tcp://0.0.0.0:7652
ts=2017-03-30T17:56:16.335721834Z level=info bulk=tcp://0.0.0.0:7653
ts=2017-03-30T17:56:16.335867229Z level=info API=tcp://0.0.0.0:7650
ts=2017-03-30T17:56:16.336286856Z level=info ingest_path=data/ingest
ts=2017-03-30T17:56:16.336555181Z level=info store_path=/data/logs
ts=2017-03-30T17:56:16.346392285Z level=debug component=cluster Join=2
ts=2017-03-30T17:56:23.447106054Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:24.447373847Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:25.44761029Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:26.347121528Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:26.547154553Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:27.547712975Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:28.547965589Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:29.647080188Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:30.647472142Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:31.347118007Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:31.647857476Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:32.747093638Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:33.747370686Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:34.747700868Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:35.847094745Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:36.347009652Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:36.847414706Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:37.847711542Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:38.947090404Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:39.947376704Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:40.947635136Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:41.347127391Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:42.047723331Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:43.048027565Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:44.048341467Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:45.147145478Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:46.147403592Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:46.347037228Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:47.147697833Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:48.247080425Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:49.247398915Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:50.247881684Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:51.347069056Z level=warn component=cluster NumMembers=1
ts=2017-03-30T17:56:51.347224787Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T17:56:52.347419488Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
^Cts=2017-03-30T17:56:53.347695549Z level=debug component=Compacter shutdown_took=7.746µs
received signal interrupt

**Comment by peterbourgon** [comment]
Your nodes can't talk to each other. Both of these commands need to work:

```
matthew@log-store-1:~$ ping log-store-2
matthew@log-store-2:~$ ping log-store-1
```

Whatever you would need to `ping` is what you need to pass as the argument to `-cluster`.

**Comment by newhook** [comment]
The nodes can talk.

matthew@log-store-1:~$ ping log-store-2
PING log-store-2.c.arched-tape-107014.internal (10.240.0.32) 56(84) bytes of data.
64 bytes from log-store-2.c.arched-tape-107014.internal (10.240.0.32): icmp_seq=1 ttl=64 time=1.22 ms
64 bytes from log-store-2.c.arched-tape-107014.internal (10.240.0.32): icmp_seq=2 ttl=64 time=0.381 ms

matthew@log-store-2:~/go/src/github.com/oklog/oklog$ ping log-store-1
PING log-store-1.c.arched-tape-107014.internal (10.240.0.24) 56(84) bytes of data.
64 bytes from log-store-1.c.arched-tape-107014.internal (10.240.0.24): icmp_seq=1 ttl=64 time=0.344 ms
64 bytes from log-store-1.c.arched-tape-107014.internal (10.240.0.24): icmp_seq=2 ttl=64 time=0.371 ms

**Comment by peterbourgon** [comment]
Bizarre. `oklog version` so I can try to reproduce? And would you mind testing out some debug version if I made it available to you?

**Comment by newhook** [comment]
I've tried both the binaries downloaded today (0.2.0) and the repo version with the same issue.  I can test whatever out (including branches from the repo if that's easier for you).

**Comment by peterbourgon** [comment]
Cool! Would you mind testing out the newly-pushed `debug` branch, starting the binaries with `-debug`? e.g.

```
cd $GOPATH/src/github.com/oklog/oklog
git fetch
git checkout debug
go install github.com/oklog/oklog/cmd/oklog
$GOPATH/bin/oklog ingeststore -debug ...
```

**Comment by newhook** [comment]
matthew@log-store-1:~/go/src/github.com/oklog/oklog$ oklog ingeststore -debug -cluster log-store-1 -peer log-store-1 -peer log-store-2 --store.path=/data/logs
ts=2017-03-30T18:30:53.526308501Z level=info cluster=log-store-1:7659
ts=2017-03-30T18:30:53.526381025Z level=info fast=tcp://0.0.0.0:7651
ts=2017-03-30T18:30:53.526399024Z level=info durable=tcp://0.0.0.0:7652
ts=2017-03-30T18:30:53.526414835Z level=info bulk=tcp://0.0.0.0:7653
ts=2017-03-30T18:30:53.526431345Z level=info API=tcp://0.0.0.0:7650
ts=2017-03-30T18:30:53.526506615Z level=info ingest_path=data/ingest
ts=2017-03-30T18:30:53.526613464Z level=info store_path=/data/logs
ts=2017-03-30T18:30:53.526921523Z level=debug component=cluster received=NotifyJoin node=42adcd4a-dd79-474c-9bea-3df53b80fc84 addr=:::7659
ts=2017-03-30T18:30:53.549034762Z level=debug component=cluster Join=1
ts=2017-03-30T18:30:53.649355533Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T18:30:53.932413727Z level=debug component=cluster received=NotifyJoin node=cd4d0c7e-f736-4633-b8c3-0db795b662d9 addr=:::7659
ts=2017-03-30T18:31:00.527527395Z level=debug component=cluster received=NotifyLeave node=cd4d0c7e-f736-4633-b8c3-0db795b662d9 addr=:::7659
ts=2017-03-30T18:31:00.549328817Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T18:31:01.549680758Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T18:31:02.550046631Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
^Cts=2017-03-30T18:31:03.17373462Z level=debug component=cluster received=NotifyLeave node=42adcd4a-dd79-474c-9bea-3df53b80fc84 addr=:::7659
ts=2017-03-30T18:31:03.549274692Z level=warn component=cluster NumMembers=0
ts=2017-03-30T18:31:03.55019442Z level=debug component=Compacter shutdown_took=3.459µs
received signal interrupt

matthew@log-store-2:~/go/src/github.com/oklog/oklog$ oklog ingeststore -debug -cluster log-store-2 -p
ts=2017-03-30T18:30:53.927714013Z level=info cluster=log-store-2:7659
ts=2017-03-30T18:30:53.927836124Z level=info fast=tcp://0.0.0.0:7651
ts=2017-03-30T18:30:53.927880832Z level=info durable=tcp://0.0.0.0:7652
ts=2017-03-30T18:30:53.927926752Z level=info bulk=tcp://0.0.0.0:7653
ts=2017-03-30T18:30:53.927955262Z level=info API=tcp://0.0.0.0:7650
ts=2017-03-30T18:30:53.9281233Z level=info ingest_path=data/ingest
ts=2017-03-30T18:30:53.928308217Z level=info store_path=/data/logs
ts=2017-03-30T18:30:53.928705325Z level=debug component=cluster received=NotifyJoin node=cd4d0c7e-f736-4633-b8c3-0db795b662d9 addr=:::7659
ts=2017-03-30T18:30:53.933204154Z level=debug component=cluster received=NotifyJoin node=42adcd4a-dd79-474c-9bea-3df53b80fc84 addr=:::7659
ts=2017-03-30T18:30:53.945543953Z level=debug component=cluster Join=2
ts=2017-03-30T18:31:00.929348478Z level=debug component=cluster received=NotifyLeave node=42adcd4a-dd79-474c-9bea-3df53b80fc84 addr=:::7659
ts=2017-03-30T18:31:01.046046872Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T18:31:02.046304457Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T18:31:03.046523781Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T18:31:03.945875474Z level=warn component=cluster NumMembers=1
ts=2017-03-30T18:31:04.146142111Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T18:31:05.146381792Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T18:31:06.146738611Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T18:31:07.246166281Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
^Cts=2017-03-30T18:31:07.860255794Z level=debug component=cluster received=NotifyLeave node=cd4d0c7e-f736-4633-b8c3-0db795b662d9 addr=:::7659
ts=2017-03-30T18:31:08.246437756Z level=debug component=Compacter shutdown_took=9.794µs
received signal interrupt

**Comment by peterbourgon** [comment]
```
ts=2017-03-30T18:30:53.928705325Z level=debug component=cluster 
  received=NotifyJoin node=cd4d0c7e-f736-4633-b8c3-0db795b662d9 addr=:::7659
ts=2017-03-30T18:30:53.933204154Z level=debug component=cluster 
  received=NotifyJoin node=42adcd4a-dd79-474c-9bea-3df53b80fc84 addr=:::7659
ts=2017-03-30T18:30:53.945543953Z level=debug component=cluster Join=2
ts=2017-03-30T18:31:00.929348478Z level=debug component=cluster 
  received=NotifyLeave node=42adcd4a-dd79-474c-9bea-3df53b80fc84 addr=:::7659
```

Your nodes are advertising themselves on what looks to be the loopback IPv6 address (`addr=:::7659`). Can you try passing the FQDN or the IP to `-cluster`?

**Comment by newhook** [comment]
That sorts things out. That said `:::7659` AFAIK isn't a ipv6 loopback address. Isn't that the ipv6 loopback address `::1`?

This is the interfaces on one of the machines:
```
matthew@log-store-1:~/go/src/github.com/oklog/oklog$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP group default qlen 1000
    link/ether 42:01:0a:f0:00:18 brd ff:ff:ff:ff:ff:ff
    inet 10.240.0.24/32 brd 10.240.0.24 scope global ens4
       valid_lft forever preferred_lft forever
    inet6 fe80::4001:aff:fef0:18/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:6a:1f:e3:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

**Comment by peterbourgon** [comment]
All I can say for sure is that `log-store-1` resolves to a non-routable address `::` when looked-up on `log-store-1`. I'm a bit perplexed that this wasn't warned-for, we have [a check for that](https://github.com/oklog/oklog/blob/master/cmd/oklog/ingeststore.go#L226-L230)

```go
// Safety warning.
if hasNonlocal(clusterPeers) && isUnroutable(clusterHost) {
	level.Warn(logger).Log("err", "this node advertises itself on an unroutable address", "addr", clusterHost)
	level.Warn(logger).Log("err", "this node will be unreachable in the cluster")
	level.Warn(logger).Log("err", "provide -cluster as a routable IP address or hostname")
}
```

**Comment by peterbourgon** [comment]
Ah, I see: the format `:::1234` fails. Fixing that...

**Comment by newhook** [comment]
matthew@log-store-1:~/go/src/github.com/oklog/oklog$ oklog ingeststore -debug -cluster log-store-1 -peer log-store-1 -peer log-store-2 --store.path=/data/logs
ts=2017-03-30T22:28:47.265830127Z level=info cluster=log-store-1:7659
ts=2017-03-30T22:28:47.265896435Z level=info fast=tcp://0.0.0.0:7651
ts=2017-03-30T22:28:47.265919027Z level=info durable=tcp://0.0.0.0:7652
ts=2017-03-30T22:28:47.265933767Z level=info bulk=tcp://0.0.0.0:7653
ts=2017-03-30T22:28:47.265950945Z level=info API=tcp://0.0.0.0:7650
ts=2017-03-30T22:28:47.266049911Z level=info ingest_path=data/ingest
ts=2017-03-30T22:28:47.266181028Z level=info store_path=/data/logs
ts=2017-03-30T22:28:47.26619697Z level=debug component=cluster cluster_addr=log-store-1 cluster_port=7659 ParseIP=<nil>
ts=2017-03-30T22:28:47.266461654Z level=debug component=cluster received=NotifyJoin node=b416de0e-f0b4-4cbc-9639-c8ed711c5593 addr=:::7659
ts=2017-03-30T22:28:47.303003256Z level=debug component=cluster Join=1
ts=2017-03-30T22:28:47.403351556Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T22:28:48.403573143Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
ts=2017-03-30T22:28:49.403793097Z level=warn component=Consumer state=gather replication_factor=2 available_peers=1 err="replication currently impossible"
^Cts=2017-03-30T22:28:49.5638198Z level=debug component=cluster received=NotifyLeave node=b416de0e-f0b4-4cbc-9639-c8ed711c5593 addr=:::7659
^Cts=2017-03-30T22:28:50.404072092Z level=debug component=Compacter shutdown_took=57.242µs
received signal interrupt

**Comment by peterbourgon** [comment]
Wow, how confusing! ParseIP returning a nil IP for that host.

**Comment by newhook** [comment]
Its calling ParseIP with the hostname not an ip address in this case since I ran with `cluster log-store-1 -peer` so I'd expect that to return nil. If I run with `-cluster 10.240.0.24` then it returns, as expected, 10.240.0.24.

**Comment by peterbourgon** [comment]
Yes, but `log-store-1` should resolve to an IP which is nonroutable, which I should detect...

**Comment by newhook** [comment]
`net.ParseIP` won't do that though? https://golang.org/src/net/ip.go?s=14972:14997#L640

**Comment by newhook** [comment]
Ok, part of the mystery solved.

:::7659 is actually `::` <- host, ':', port 7659.

If you look at hashicorp/memberlist/net_transport.go
`func (t *NetTransport) FinalAdvertiseAddr(ip string, port int) (net.IP, int, error) {`

It ends up resolving the host using `advertiseAddr = t.tcpListeners[0].Addr().(*net.TCPAddr).IP` which ends returns `::`.

If BindAddrs was set I think it would work correctly. I tried this by hacking the code and it indeed worked:

`ts=2017-03-30T22:55:26.79587313Z level=debug component=cluster received=NotifyJoin node=74bf232e-91b1-4742-91c8-baca995ed97a addr=10.240.0.24:7659`

**Comment by peterbourgon** [comment]
If you wanted to give the latest in master a try, you should see improved warning messages. There's also an optional -cluster.advertise-addr flag you can use to explicitly set the advertise address, if you don't want it to be derived from the -cluster bind address.
