### ISSUE TITLE
Documentation by example 

### ISSUE THREAD

**Issue by ProPheT777** [oklog/oklog#64]
Hey, 

Your project look very promissing and very interesing however I can't figured out how start to use this tool :/ 

I only know how to plug docker with logspout forwarder to oklog ingester from the documentation and ... that's all. 

I'm looking to integrate oklog in docker-compose stack, my questions are : 

- How register the oklog ingester ? (command line, config) 
- How expose the ui ? (command line to execute, port exposed ?) 
- Forward is explained, so it's ok :+1: 

Could you provide or explain me how to archieve it (in order to provide a docker-compose example as PR) please ? 

Thank you

**Comment by peterbourgon** [comment]
Everything is comprehensively documented in the README. I'm not going to provide docker-compose examples as (a) I don't use the tool, and (b) they would be an ongoing maintenance burden. Sorry! :)

**Comment by peterbourgon** [comment]
Ah, I will update the README to document how to get at the UI.

**Comment by peterbourgon** [comment]
Done.

**Comment by ProPheT777** [comment]
Ok, thank you !
