### ISSUE TITLE
Update README with build instructions

### ISSUE THREAD

**Issue by sivasamyk** [oklog/oklog#65]
I am a newbie to golang. It would be great if you add build instructions in README. 
When I try to clone the repo and build `dep ensure` is giving me following error:

`split absolute project root: /home/user/projects/oklog/oklog not in any $GOPATH`

My GOPATH is `/home/user/projects/oklog/` and project root is in `/home/user/projects/oklog/oklog`
 I am sure I am doing something wrong here.

**Comment by moderation** [comment]
The simple way I have worked out to build from master is to simply run:
`go get -u github.com/oklog/oklog/cmd/oklog`

You can rebuild after a master commit by adding the -u
`go get -u github.com/oklog/oklog/cmd/oklog`

Assuming you have your Go set up that should put the oklog binary in your path.

**Comment by peterbourgon** [comment]
You shouldn't be building from source — [download a release](https://github.com/oklog/oklog/releases)! :)

**Comment by sivasamyk** [comment]
@peterbourgon Thanks.  I am asking from developer perspective who is trying to make some code changes.

**Comment by peterbourgon** [comment]
With respect, this is not a good project for Go newbies to dive in to :)
