### ISSUE TITLE
Structured logging and querying a single column in a large data set

### ISSUE THREAD

**Issue by pkieltyka** [oklog/oklog#70]
Hey @peterbourgon great project.

I was quickly reading the source and it looks like you're creating append-only segments of the raw logs and for queries you traverse the full set of logs from a small chunk of time.

My use case is to send structured logs to oklog and search along a column for a large data set over a large period of time and keeping the queries fast (<100ms per search result set).

Have you considered using an embedded db (ie. like github.com/dgraph-io/badger) that could potentially offer the building blocks to add support for structured logging schema's, adapters, and indexing?

it would be cool to hook up bleve to certain columns too

**Comment by peterbourgon** [comment]
As a component of OK Log itself, definitely not: that's for sure out of scope. But I'm happy to improve the e.g. streaming API to make integration with an indexer easier. Concrete ideas there?

**Comment by pkieltyka** [comment]
@peterbourgon yea, that makes sense to have an indexer on top of oklog.

Let me know what you think would be the right approach, but some options I see:

* A client (the indexer) could connect to any oklog host in the cluster and inform oklog to stream information to that client over tcp or http
* Start oklog stream process and pass a destination host parameter (tcp or http) for process to pipe information (Im not sure if that process/node would have all the data though, not sure how its segmented if at all across nodes in the cluster?)
*  Oklog could just be embedded into a larger project for structure logging and handling these concerns, with the APIs built directly into the project, where each node would offer a new store.Log, etc implementation to its persistent store (the indexer)
* NATS could be an interesting transport here too depending on how data might flow

**Comment by peterbourgon** [comment]
There's already a stream API that an indexer can call, on any store or ingeststore node. Can you use it? — I like the idea of keeping a process boundary between OK Log and a structured or indexing server, but if you have concrete problems you need to solve where that represents a problem, I'd love to hear them.

**Comment by pkieltyka** [comment]
ah cool, I'll check out ingest / ingeststore. I'm sure these will get me started.
