### ISSUE TITLE
Use oklog/pkg/group with async Run methods.

### ISSUE THREAD

**Issue by krasi-georgiev** [oklog/oklog#74]
after watching your amazing talk for run groups 
https://youtu.be/LHe1Cb_Ud_M?t=1487

I decided to refactor the `main.go` in  prometheus.
https://github.com/prometheus/prometheus/issues/3246

Some of the Run methods are async so when I put it in a group it triggers a teardown.
https://github.com/prometheus/prometheus/blob/master/rules/manager.go#L380
the package still has .Stop method which should run on app exit.

I see 2 options:
1. refactor all .Run methods to be blocking
2. put the async Run-ers in the same group as a single blocking one and group destructors the same way.

I prefer option 1 , where option 2 would be easier to implement so  it would be interesting to hear a second opinion.

some Packages wouldn't make sense to have a blocking constructor but still need a destructor.

**Comment by peterbourgon** [comment]
Yeah, that sucks. Run methods as envisioned by package group must not be async. That would defeat the purpose. It should be easy-ish to adapt, though:

```go
type Thing struct{ ... }

func (t *Thing) Start() { ... } // async
func (t *Thing) Stop()  { ... } // sync

var g group.Group
{
    done := make(chan struct{})
    g.Add(func() error {
        t.Start()     // returns immediately
        <-done        // blocks until the interrupt function successfully kills Thing
    }, func(error) {
        t.Stop()      // tell Thing to die, and wait for it
        close(done)   // signal the execute function to return
    })
}
```

**Comment by peterbourgon** [comment]
That assumes Stop is sync. If that's not true then we need some other way to know when a component is actually shut down. If the component has no way to communicate that information to the outer context, then the component needs to be refactored somehow.

**Comment by krasi-georgiev** [comment]
great idea , I will try and let you know how it went.

**Comment by krasi-georgiev** [comment]
still WIP but I like the new structure
https://github.com/prometheus/prometheus/pull/3251
