### ISSUE TITLE
Feature request - append string to every line

### ISSUE THREAD

**Issue by yellowmegaman** [oklog/oklog#75]
Thanks for great tool!
I'd like to have ability to add string to every line of logs. 
#### Example:
`/usr/bin/cassandra | oklog -logstring "cassandra-$(hostname)"`

That way we would be able to query only for cassandra logs, query for particular cassandra node logs.
We're using lots of databases and server tools, configuring log format for all of them is pain, and sometimes there's no option for it.

With this addition we could "override" log format for every app to make it query-friendly.

Thanks a lot in advance! Please tell me what do you think.

**Comment by xla** [comment]
Hej @yellowmegaman did you look into the `-prefix` flag of the forward command and if that would enable your use-case?

**Comment by yellowmegaman** [comment]
Just found it and went here to close the issue ;)

Thanks a bunch!
