### ISSUE TITLE
Question: trying to figure out if OK Log is right for me

### ISSUE THREAD

**Issue by inklit** [oklog/oklog#77]
### Introduction:
Hi there, sorry in advance for what are probably silly questions.

I am looking to replace my current logging system, which is rather complex and has a lot of weird intricacies that are rather annoying.

### Here is information about my current logging system (some good, some bad):
**1**: The log system is not live. It uses a collection system to _periodically_ collect the logs from each host (there's about 32 hosts total, and logs are collected/processed/stored every week usually, but sometimes shorter periods based on log volume)

**2**: It collects logs from the Windows Event Logger, which is not cross platform and a huge pain to work with. I can pipe out from the Windows Event Logger, but it's slow and non-performant. Most of my logs do not end up in the stdout of the programs we run.
Logs are stored locally in the Windows Event Logger until collected by our centralized log manager.
This can definitely be re-worked, but I am unsure whether or not it'd be a **good idea** to rework this, considering item 3.

**3**: The amount of logs that are recorded is in the hundreds per second. We store a log for many different events which adds up extremely quickly.
When we collect logs, we process and store about 40 million logs per week per host (1.2 billion logs per week total)
_**(What's considered a "large log volume" in OK Log?)**_

**4A**: The logs are searched with an "SQL-like" querying language. 
**4B**: Each "type" of log is manually defined with types, the types get stored instead of the string version of the log. This reduces storage space and is required for the "SQL-like" querying language to work. There is about 2000 different types of logs for various different events. All log output from the programs we run are strictly based on these types we've defined in the logging system.
_**(How flexible is OK Log's search?)**_

**5**: The logs must be stored and searchable with a retention of 1 year (or more). This would be about 62.4 billion logs.
_**(OK Log has a default retention of 7 days, is it viable to use such a long retention period with OK Log, especially at our scale?)**_

**6**: It takes about 5-30 minutes to query the log system for specific data. This is extremely problematic when we are trying to track down a specific problem, because 1 problem may have thousands of different log types and data related to it.
**_(How fast can OK Log query massive amounts of logs, more specifically in the numbers of 62.4 billion logs?)_**

**7**: The logs are dumped from the main storage server then archived/backed up every 3 months or so. Logs that are backed up are no longer searchable (until manually imported) and stored for about 2 years. They don't get removed from the main server until 1 year as mentioned in item 5.
_**(How easy is it to "back up" logs in OK Log? If you do back them up, how easy is it to query them again after they've been in dormant storage for a long time?)**_

### Conclusion:
So my main question is: Considering all this information, is OK Log right for me?
I've been having troubles finding a logging solution to replace this that will work at our massive scale.
If you don't think OK Log is right for me, do you know of any other solutions that can replace this system?

**Comment by peterbourgon** [comment]
> What's considered a "large log volume" in OK Log?

OK Log imposes very little overhead, you're generally constrained by your hardware: disk iops (ingesters, stores), disk size (stores), and bandwidth (all). I've personally benchmarked an OK Log cluster up to just about 1GBps aggregate ingest rate. The number of individual logs per second is kind of irrelevant, the more important question is how big they are.

> How flexible is OK Log's search?

OK Log's search is time-bounded grep. If you want something more than that, you need to hook up an e.g. search indexing system to the OK Log stream endpoint.

> OK Log has a default retention of 7 days, is it viable to use such a long retention period with OK Log, especially at our scale?

OK Log isn't really designed to be a long-term log archival system. Any retention period longer than (say) a month makes me raise my eyebrows. With that said, I guess there isn't any fundamental reason it wouldn't work. Please test it out with synthesized data and let me know what doesn't work well.

> How fast can OK Log query massive amounts of logs, more specifically in the numbers of 62.4 billion logs?

OK Log's time-bounded grep search is basically as fast as grepping the same corpus on local disk. Again, the number of logs is kind of irrelevant, the important criteria is how big they are. If you need more sophisticated querying than grep, you need to hook up an e.g. search indexing system to the OK Log stream endpoint.

> How easy is it to "back up" logs in OK Log? If you do back them up, how easy is it to query them again after they've been in dormant storage for a long time?

OK Log stores logs as flat files on disk, uncompressed and unencoded, with each record being assigned a unique ULID prefix. You're free to back those files up however you like. OK Log doesn't natively support an export/import to cold storage workflow.

Hopefully this answers your questions?
