### ISSUE TITLE
How to use with a service like Heroku?

### ISSUE THREAD

**Issue by zombor** [oklog/oklog#78]
Hey there, I'd like to use OKLog, but I'm struggling figuring out a good way to run it with my heroku app. The "best" thing I've come up with is:

Copy `cmd/oklog` into my app's directory and let heroku compile it and make it available (heroku automatically compiles and makes things in `cmd/` available to run). I could then pipe my app into `oklog` in my `Procfile`.

The only downside to this is it seems that my `STDOUT` will be swallowed by `oklog` and I'll lose `heroku logs`.

Is there a better way?

**Comment by xla** [comment]
It seems that you might be better of with utilising there log infrastructure and specifically [Log Drains](https://devcenter.heroku.com/articles/log-drains) which can be configured to ship your application logs to external services.

Out of curiosity what are your requirements to get your logs out of a PaaS like Heroku into a system like OK Log?

**Comment by zombor** [comment]
> what are your requirements to get your logs out of a PaaS like Heroku into a system like OK Log?

I currently use Papertrail for logs but I already have a hosted server that I use for prometheus metrics and I'd like to get everything self hosted and stop paying for Papertrail.

> you might be better of with utilising there log infrastructure and specifically Log Drains

I did read about these, but oklog doesn't do syslog or http POST like it wants, right? So I'd have to run a new server that did the drain conversion to `oklog forward` ?

**Comment by danp** [comment]
@zombor you can probably make use of tee and some shell magic to have output go to both oklog and still make it to stdout/stderr for `heroku logs`

**Comment by zombor** [comment]
Ah yep! A `Procfile` like

```Procfile
web: api | tee >(oklog forward $OKLOG_HOST)
```

Seems to do the trick nicely. With this method I'm still including the `cmd/oklog` source files in my project, but I suppose that shouldn't be a big problem since my app is a go app. I'm not sure how I'd do this if it was ruby or something else.

**Comment by danp** [comment]
You might want to do something like `api 2>&1 | tee ...` so you get both stdout and stderr going through tee.

**Comment by zombor** [comment]
Yeah, good idea. Any thoughts about how to run this in non-go apps? Do I just need to commit the binary into my ruby repo?

**Comment by danp** [comment]
Yeah, or perhaps make an oklog buildpack which downloads it from somewhere it build time.

**Comment by peterbourgon** [comment]
I _believe_ OK Log supports syslog, in the sense that if you connect to OK Log as if it were a syslog server, it will dutifully accept and persist the writes — in that weird syslog format :) Worth verifying, though.

**Comment by zombor** [comment]
I ended up making this heroku buildpack: https://github.com/zombor/heroku-oklog-buildpack

Works great!
