### ISSUE TITLE
CORS support on GET /query

### ISSUE THREAD

**Issue by zombor** [oklog/oklog#79]
Hi, I'm working on a javascript web frontend to query my json formatted structured logs.

I ran into a snag while getting the data from the `/query` api endpoint: there's no CORS support so cross domain javascript queries fail.

Is this something that's desirable to add? If so I can submit a PR.

**Comment by peterbourgon** [comment]
Yeah, PR happily accepted for that.

**Comment by peterbourgon** [comment]
Yeah, PR happily accepted for that.
