### ISSUE TITLE
Instructions for building the UI?

### ISSUE THREAD

**Issue by maxhawkins** [oklog/oklog#83]
Are the any instructions for building the UI code?

I'd like to make a pull request but I don't know how to use Elm.

**Comment by annismckenzie** [comment]
Looks like @xla has created a similar UI in lifesum/configsum and in that project there's a Makefile: https://github.com/lifesum/configsum/blob/master/ui/Makefile. Looks like just Elm needs to be installed.

**Comment by xla** [comment]
@maxhawkins As @annismckenzie kindly pointed out the [Makefile](https://github.com/lifesum/configsum/blob/master/ui/Makefile) from the Configsum project follows the same setup at some point similar tooling will be present. Until then make sure to start your `ingeststore` or `store` with the `-ui.local` flag for local development.

**Comment by xla** [comment]
Also be interested in the changes you'd like to propose.

**Comment by maxhawkins** [comment]
Here's the change: #84 

It's a small one. I need the UI to make requests using relative paths so I can use oklog through the Kubernetes proxy.

Thanks for the help!
