### ISSUE TITLE
Record shortWrites when forward

### ISSUE THREAD

**Issue by lizhaohui836** [oklog/oklog#92]
Thanks for providing such a good project. I am a golang beginner and I am not good at English. I am studying your code these days and found an uncertain problem.
According to my understanding, the lines 200-209 of forward.go, record will be send to conns and there is a judgments of success.  But at shortWrites statement (n < len(record)+1),
the length of prefix should be added? Sorry my poor English again. 
code for now:
      
                    record := s.Text()
			if n, err := fmt.Fprintf(conn, "%s%s\n", prefix, record); err != nil {
				disconnects.Inc()
				level.Warn(logger).Log("disconnected_from", target.String(), "due_to", err)
				break
			} else if n < len(record)+1 {
				shortWrites.Inc()
				level.Warn(logger).Log("short_write_to", target.String(), "n", n, "less_than", len(record)+1)
				break // TODO(pb): we should do something more sophisticated here
			}

code is it correct?

                    record := fmt.Sprintf("%s%s\n", prefix, s.Text())
			if n, err := fmt.Fprintf(conn, record); err != nil {
				disconnects.Inc()
				level.Warn(logger).Log("disconnected_from", target.String(), "due_to", err)
				break
			} else if n < len(record) {
				shortWrites.Inc()
				level.Warn(logger).Log("short_write_to", target.String(), "n", n, "less_than", len(record))
				break // TODO(pb): we should do something more sophisticated here
			}

**Comment by peterbourgon** [comment]
Yes! Good catch!
