### ISSUE TITLE
UI: withCredentials is False, breaks basic or cookie auth

### ISSUE THREAD

**Issue by drdaeman** [oklog/oklog#97]
Hi!

I'm not sure why `withCredentials` is set to `False`. Wouldn't it make sense to make it `True` instead?

Use case: I have thought of putting a simple HTTP Basic auth on reverse proxy that routes to OK Log, so it can be semi-safely exposed to the Internet. However, because Authorization header is not passed along the request, the UI does not work.

**Comment by xla** [comment]
Thanks for the report, where you able to confirm this fix, or would you be able to test a branch which addresses the change?

**Comment by drdaeman** [comment]
@xla Found a minute to make changes and test them. Seems that what I've proposed was not enough, but I've figured it out got everything working. Please see #98.

**Comment by xla** [comment]
Thanks for the contribution, #98 is merged.
